
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sshd-sfset
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: sshd-sfset-container
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
