#
# Service exposing SSH to the outside world
#
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: sshd-svc
  labels:
    app: sshd-svc
spec:
  loadBalancerIP: 0.0.0.0 
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: sshd-sfset
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
