apiVersion: v1
kind: Service
metadata:
  labels:
    app: sshd-svc
    instance: production
  name: sshd-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 9.8.7.6
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: sshd-sfset
    instance: production
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: background-worker-dep
    instance: production
  name: background-worker-dep
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: background-worker-dep
      instance: production
  template:
    metadata:
      labels:
        app: background-worker-dep
        instance: production
    spec:
      containers:
      - args:
        - |
          /usr/sbin/crond -f -d 8
        command:
        - /bin/sh
        - -c
        image: eu.gcr.io/<PROJECT_ID>/background-worker-container:900b447
        imagePullPolicy: Always
        name: background-worker-dep-container
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    instance: production
  name: sshd-sfset
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sshd-sfset
      instance: production
  serviceName: sshd-subdomain
  template:
    metadata:
      labels:
        app: sshd-sfset
        instance: production
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /usr/sbin/sshd -De
        image: eu.gcr.io/<PROJECT_ID>/sshd-container:900b447
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 22
        name: sshd-sfset-container
        ports:
        - containerPort: 22
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 22
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
      subdomain: sshd-subdomain
  updateStrategy:
    type: RollingUpdate
